//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginRegisterWithSession.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UsersTbl
    {
        public int UserId { get; set; }

        [Display(Name = "Username")]
        [Required(ErrorMessage = "Username is required...!")]
        public string UserName { get; set; }

        [Display(Name = "Email Address")]
        [Required(ErrorMessage = "Email Address is mandatory...!")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "Email is not valid.")]
        public string UserEmail { get; set; }

        [Display(Name = "Password")]
        [Required(ErrorMessage = "Password is required, you idiot...!")]
        [StringLength(100, MinimumLength = 8, ErrorMessage = "The password must be at least 8 characters long...!")]
        [DataType(DataType.Password)]
        public string UserPassword { get; set; }

        [Display(Name = "Confirm Password")]
        [Required(ErrorMessage = "Password confirmation is mandatory, dumbo...!")]
        [DataType(DataType.Password)]
        [Compare("UserPassword", ErrorMessage = "Password mismatch, Akhrout...!")]
        public string ConPassword { get; set; }

        [Display(Name = "Age")]
        [Required(ErrorMessage = "Please Specify your age...!")]
        [Range(18, 60, ErrorMessage = "Age Must be between 18 to 60")]
        public int UserAge { get; set; }

        [Display(Name = "Contact Number")]
        [Required(ErrorMessage = "Contact number is mandatory...!")]
        [DataType(DataType.PhoneNumber)]
        public int UserContact { get; set; }

        [Display(Name = "Gender")]
        [Required(ErrorMessage = "Please Specify your gender...!")]
        public string UserGender { get; set; }
    }
}
